name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          GITHUB_REPO: ${{ github.repository_url  }}
        run: |
          npm run build
          git config --global user.name "Akshitha"
          git config --global user.email "akshithasomisetty@gmail.com"
          git remote add origin https://github.com/SomisettySaiAkshitha1410/flashcard.git
          git push --force origin master:gh-pages
        working-directory: frontend/public
